CXX = g++
CXXFLAGS = -Wall -std=c++11

TARGET = rectangle
SRCS = main.cpp Point.cpp Rectangle.cpp
OBJS = $(SRCS:.cpp=.o)

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: clean 