/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "get.h"
/* Header for class com_mi_cc_http_MainActivity */

#ifndef _Included_com_mi_cc_http_MainActivity
#define _Included_com_mi_cc_http_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mi_cc_http_MainActivity
 * Method:    get
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mi_cc_http_MainActivity_get
  (JNIEnv *env, jobject jobj, jstring url) {
    //使用这种方式，请求回来数据返回给java层
    //char *buf;
    //get(url, &buf);
}

#ifdef __cplusplus
}
#endif
#endif
